DROP DATABASE IF EXISTS test1;
CREATE DATABASE test1;
USE test1;
DROP TABLE IF EXISTS tab1;
CREATE TABLE tab1 (
    recordID INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) DEFAULT NULL
);
INSERT INTO tab1(name) VALUES('Fred');
INSERT INTO tab1(name) VALUES('Freda');
SELECT * FROM tab1;
